from typing import Literal

from pydantic import BaseModel, Field


class AspectInsight(BaseModel):
    """
    Aspect-level sentiment insight generated by the
    CineView aspect analyzer.
    """

    name: str
    sentiment: Literal[
        "Positive",
        "Negative",
        "Neutral",
    ]
    score: int
    evidence: list[str] = Field(
        default_factory=list
    )


class ReviewRequest(BaseModel):
    """
    Request body for movie review analysis.
    """

    review: str = Field(
        ...,
        min_length=1,
        max_length=10_000,
        description="Movie review text to analyze.",
    )


class SentimentResult(BaseModel):
    """
    Overall sentiment prediction returned by the GRU.
    """

    sentiment: Literal[
        "Positive",
        "Negative",
    ]
    confidence: float
    positive_probability: float
    negative_probability: float
    aspects: list[AspectInsight] = Field(
        default_factory=list
    )


class ReviewAnalysisResponse(BaseModel):
    """
    Complete CineView review analysis response.
    """

    review: str
    result: SentimentResult